services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: familydex_dev
      POSTGRES_USER: familydex
      POSTGRES_PASSWORD: familydex
      POSTGRES_HOST_AUTH_METHOD: md5   # compatibilidad con pg node driver en Windows
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

volumes:
  postgres_data:
